---
logins:
- subject: "admin"
  secret: "sk-d77fa332-4077-4bd8-a3cb-a9d460976cd0"
  publicKey: "pk-508b2f2a-872d-4efa-9a75-b099927754c0"
  roles:
  - name: "Admin"
roles:
- name: "Admin"
- name: "User"
