# Use an existing docker image as a base
FROM ibmcom/mq

# environment
ENV LICENSE=accept

# Queue manager
ENV MQ_QMGR_NAME=QM1

# Tell the image what to do when it starts as a container
EXPOSE 1414


#ENV MQ_APP_PASSWORD=/your password here/
