version: '3'
services:
  nats-server:
    image: 'nats'
    ports:
      - "4222:4222"
  ibm-mq:
    image: 'ibmcom/mq'
    environment:
      - LICENSE=accept
      - MQ_QMGR_NAME=QM1
      - MQ_APP_PASSWORD=passw0rd
    ports:
      - "1414:1414"
  active-mq:
    image: 'vromero/activemq-artemis'
    environment:
      - ARTEMIS_USERNAME=cloudurable
      - ARTEMIS_PASSWORD=cloudurable
    ports:
      - "8161:8161"
      - "61616:61616"
  bridge-core:
    container_name: bridge-core
    image: 'cloudurable/docker-nats-bridge'
    working_dir: /usr/app/core
    command: ["sleep","infinity"]
    #command: bash -c "sleep 30 && ./gradlew clean test"
    #command: bash -c "sleep 30 && NATS_BRIDGE_JMS_USER=cloudurable NATS_BRIDGE_JMS_PWD=cloudurable NATS_BRIDGE_NATS_SERVERS=nats://nats-server:4222 NATS_BRIDGE_JMS_CONNECTION_FACTORY=tcp://active-mq:61616 ./gradlew clean test"
  bridge-admin:
    container_name: bridge-admin
    image: 'cloudurable/nats-bridge-admin'
    working_dir: /usr/app/admin
    #command: ["sleep","infinity"]
    command: bash -c "./gradlew bootRun"
    ports:
      - "8080:8080"
  prometheus:
    build:
      context: .
      dockerfile: Dockerfile_prometheus.dev
    ports:
      - "9090:9090"
