# Use an existing docker image as a base. This gets used by Travis integration testing to test core
# This is used to run the travis tests
# Copies code to this container and then runs gradle build
FROM cloudurable/gradle

#Copying files
COPY . ./usr/app

WORKDIR /usr/app/core

ENV JAVA_HOME /root/.sdkman/candidates/java/current

CMD bash -c "sleep 30 && NATS_BRIDGE_JMS_USER=cloudurable NATS_BRIDGE_JMS_PWD=cloudurable NATS_BRIDGE_NATS_SERVERS=nats://nats-server:4222 NATS_BRIDGE_JMS_CONNECTION_FACTORY=tcp://artemis-server:61616 ./gradlew clean test"
