# Build latest version of app and install in docker container 
FROM cloudurable/gradle

#Copying files
COPY . ./usr/app

WORKDIR /usr/app/core

ENV JAVA_HOME /root/.sdkman/candidates/java/current

#Build Core
WORKDIR /usr/app/core
RUN bash -c "./gradlew clean build publishToMavenLocal -x test"

#Build Admin
WORKDIR /usr/app/admin
RUN bash -c "./gradlew build -x test"

WORKDIR /usr/app
