# Use an existing docker image as a base
FROM vromero/activemq-artemis

# environment
ENV ARTEMIS_USERNAME=cloudurable
ENV ARTEMIS_PASSWORD=cloudurable

# Tell the image what to do when it starts as a container
EXPOSE 8161
EXPOSE 61616
