version: '3'
services:
  nats-server:
    build:
      context: ../bridge-nats-server
    ports:
      - "4222:4222"
      - "8222:8222"
  ibm-mq:
    build:
      context: ../bridge-ibmmq
    environment:
      - LICENSE=accept
      - MQ_QMGR_NAME=QM1
      - MQ_APP_PASSWORD=passw0rd
    ports:
      - "1414:1414"
      - "9443:9443"
  active-mq:
    build:
      context: ../bridge-activemq
    ports:
      - "8161:8161"
      - "61616:61616"
  prometheus:
    build:
      context: ../prometheus
    environment:
      - TARGET=host.docker.internal
    ports:
      - "9090:9090"
