name: GitHub Build Actions For Nats JMS Bridge

on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
  push:
    branches:
      - main
  release:
    branches:
      - main
    types: [released]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_EVENT: ${{ github.event_name }}
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
      SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Generate wrappers and prepare gradle
        run: bin/build.sh wrapper_and_chmod
      - name: Build Messages Lib
        run: ./gradlew clean build publishToMavenLocal
        working-directory: ./message
      - name: Build Core Lib
        run: ./gradlew clean build publishToMavenLocal -x test
        working-directory: ./core
      - name: Build Bridge Admin Server
        run: ./gradlew clean distZip publishToMavenLocal -x test
        working-directory: ./admin
      - name: Build Examples
        run: ./gradlew clean build
        working-directory: ./examples
      - name: Build Example Transforms
        run: ./gradlew clean build
        working-directory: ./example-transform
      - name: Build Maven Bridge
        run: mvn clean compile
        working-directory: ./mavenBridge
      - name: Merge to Main, Publish Messages Lib Snapshot
        if: ${{ success() && github.event_name == 'push' }}
        run: ./gradlew publishToSonatype
        working-directory: ./message
      - name: Merge to Main, Publish Core Lib Snapshot
        if: ${{ success() && github.event_name == 'push' }}
        run: ./gradlew publishToSonatype
        working-directory: ./core
      - name: Merge to Main, Publish Admin Snapshot
        if: ${{ success() && github.event_name == 'push' }}
        run: ./gradlew publishToSonatype
        working-directory: ./admin
      - name: Tag Release Main, Sign and Publish Messages Lib Release
        if: ${{ success() && github.event_name == 'release' }}
        run: ./gradlew -i signArchives signMavenJavaPublication publishToSonatype closeAndReleaseSonatypeStagingRepository
        working-directory: ./message
      - name: Tag Release Main, Sign and Publish Core Lib Release
        if: ${{ success() && github.event_name == 'release' }}
        run: ./gradlew -i signArchives signMavenJavaPublication publishToSonatype closeAndReleaseSonatypeStagingRepository
        working-directory: ./core
      - name: Tag Release Main, Sign and Publish Admin Release
        if: ${{ success() && github.event_name == 'release' }}
        run: ./gradlew -i signArchives signMavenJavaPublication publishToSonatype closeAndReleaseSonatypeStagingRepository
        working-directory: ./admin
