name: GitHub Build Actions For Nats JMS Brdige

on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
  push:
    branches:
      - main
  release:
    branches:
      - main
    types: [released]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      BUILD_EVENT: ${{ github.event_name }}
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
      SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Docker Create Network
      run: docker network create bnet
    - name: Generate wrappers to match local verison
      run: bin/build.sh wrapper_and_chmod
    - name: Build Messages Lib
      run: ./gradlew clean build publishToMavenLocal
      working-directory: ./message
    - name: Build Core Lib
      run: ./gradlew clean build publishToMavenLocal -x test
      working-directory: ./core
    - name: Build Bridge Admin Server
      run: ./gradlew clean distZip
      working-directory: ./admin
    - name: Cleanup
      if: ${{ always() }}
      run: docker network remove bnet
