name: Publish Nats JMS Bridge Snapshots

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      BUILD_EVENT: publish_snapshot
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
      SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Generate wrappers and prepare gradle
      run: bin/build.sh wrapper_and_chmod
    - name: Build Messages Lib
      run: ./gradlew clean build publishToMavenLocal publishToSonatype -i
      working-directory: ./message
    - name: Build Core Lib
      run: ./gradlew clean build publishToMavenLocal publishToSonatype -x test -i
      working-directory: ./core
